version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.4
    restart: always
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ch_data:/var/lib/clickhouse
    # use host mode so we can export span from ClickHouse to Uptrace
    network_mode: host
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'
        loki-external-labels: 'type=docker,container_name={{.Name}}'

  grafana:
    image: grafana/grafana:8.5.2
    restart: always
    volumes:
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/custom.ini:/etc/grafana/grafana.ini
    # use host mode so we can use Uptrace datasource
    network_mode: host

  cloki:
    image: qxip/cloki:latest
    restart: always
    environment:
      CLICKHOUSE_SERVER: clickhouse
      CLICKHOUSE_DB: uptrace
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - '3100:3100' # UI and HTTP API

volumes:
  ch_data:
    driver: local
