apiVersion: 1

deleteDatasources:
  - name: cLoki
    orgId: 1
  - name: Uptrace
    orgId: 1

datasources:
  - name: cLoki
    type: loki
    access: proxy
    url: http://localhost:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: Uptrace
          matcherRegex: ".*/traces/(?\u003ctraceId\u003e.*)"
          name: 'traceId'
          url: '${__value.raw}'
      # Field with external link.
      # - matcherRegex: "traceID=(\\w+)"
      #   name: TraceID
      #   url: "http://localhost:14318/traces/1/${__value.raw}"
  - name: Uptrace
    type: tempo
    access: proxy
    url: http://localhost:14318
    editable: true
