apiVersion: 1

datasources:
  - name: Uptrace Prometheus Project 1
    type: prometheus
    access: proxy
    url: http://host.docker.internal:14318/api/prometheus
    editable: true
    jsonData:
      httpHeaderName1: 'uptrace-dsn'
    secureJsonData:
      httpHeaderValue1: 'http://project1_secret_token@localhost:14317/1'

  - name: Uptrace Prometheus Project 2
    type: prometheus
    access: proxy
    url: http://host.docker.internal:14318/api/prometheus
    editable: true
    jsonData:
      httpHeaderName1: 'uptrace-dsn'
    secureJsonData:
      httpHeaderValue1: 'http://project2_secret_token@localhost:14317/2'
