version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.4
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ch_data:/var/lib/clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  uptrace:
    #image: 'uptrace/uptrace:latest'
    image: 'uptrace/uptrace-dev:latest'
    volumes:
      - ./uptrace.yml:/etc/uptrace/uptrace.yml
    ports:
      - '14317:14317' # OTLP
      - '14318:14318' # UI and HTTP API
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - DEBUG=2
    depends_on:
      clickhouse:
        condition: service_healthy

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.58.0
    restart: on-failure
    volumes:
      - ../../config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    # use host mode so we can export data to Uptrace
    network_mode: host

  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports:
      - '8080:8080'
    command: ['all', '-j', 'http://localhost:14318']
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - otel-collector

volumes:
  ch_data:
    driver: local
