blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/uptrace/uptrace/discussions
    about: Ask a question via GitHub Discussions
  - name: Discord Chat
    url: https://discord.gg/YF8tdP8Pmk
    about: Ask a question or chat on Discord server
