extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
  jaeger:
    protocols:
      grpc:
  filelog/syslog:
    include: ['/var/log/syslog']
    start_at: beginning
    operators:
      - type: add
        field: attributes.log.source
        value: syslog
  filelog/docker:
    include: ['/var/lib/docker/containers/*/*.log']
    start_at: end
    include_file_path: true
    include_file_name: false
    resource: { 'log.source': 'docker' }
    operators:
      - type: json_parser
        id: parser-docker
        output: extract_metadata_from_filepath
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      - type: regex_parser
        id: extract_metadata_from_filepath
        regex: '^.*containers/(?P<container_id>[^_]+)/.*log$'
        parse_from: attributes["log.file.path"]
        output: parse_body
      - type: move
        id: parse_body
        from: attributes.log
        to: body
        output: time
      - type: remove
        id: time
        field: attributes.time

processors:
  resourcedetection:
    detectors: ['system']
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: localhost:14317
    tls:
      insecure: true
    headers: { 'uptrace-dsn': 'http://project1_secret_token@localhost:14317/1' }

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [otlp, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics/hostmetrics:
      receivers: [hostmetrics]
      processors: [batch, resourcedetection]
      exporters: [otlp]
    logs:
      receivers: [otlp, filelog/syslog, filelog/docker]
      processors: [batch]
      exporters: [otlp]

  extensions: [health_check, pprof, zpages]
