groups:
  - name: example
    rules:
      - alert: high number of spans
        expr: uptrace_projects_spans{} > 0
        for: 1m
        labels:
          foo: bar
        annotations:
          summary: High number of spans
