##
## You can use environment variables anywhere in this file, for example:
##
##   foo: $FOO
##   bar: ${BAR}
##   $BAZ: baz
##
## To escape `$`, use `$$`, for example:
##
##   foo: $$FOO_BAR
##

# Enable to log HTTP requests and ClickHouse queries.
debug: false

# Secret key that is used to sign JWT tokens etc.
secret_key: changeme

listen:
  # OTLP/gRPC API
  grpc: ':14317'
  # OTLP/HTTP API and Uptrace HTTP API
  http: ':14318'

# Public URL for Vue-powered UI.
site:
  addr: 'http://localhost:14318'

ch:
  # Connection string for ClickHouse database. For example:
  # clickhouse://<user>:<password>@<host>:<port>/<database>?sslmode=disable
  #
  # See https://clickhouse.uptrace.dev/
  dsn: 'clickhouse://default:@localhost:9000/uptrace?sslmode=disable'

# Various options to tweak ClickHouse schema.
ch_schema:
  # Compression codec, for example, LZ4 or ZSTD(3).
  compression: ZSTD(3)

  # Whether to create ReplicatedMergeTree instead of MergeTree.
  #replicated: false

  # Cluster name for Distributed tables and ON CLUSTER clause.
  #cluster: uptrace1

# Spans processing options.
spans:
  # Delete data after 30 days.
  # Supports SQL interval syntax, for example, INTERVAL 30 DAY.
  ttl: 30 DAY

  # The size of Go chan used to buffer incoming spans.
  # If the buffer is full, Uptrace starts to drop spans.
  #buffer_size: 100000

  # The number of spans to insert in a single query.
  #batch_size: 10000

# Metrics processing options.
metrics:
  # Delete data after 30 days.
  # Supports SQL interval syntax, for example, INTERVAL 30 DAY.
  ttl: 90 DAY

  # List of attributes to drop for being noisy.
  drop_attrs:
    - telemetry.sdk.language
    - telemetry.sdk.name
    - telemetry.sdk.version

  # The size of Go chan used to buffer incoming measures.
  # If the buffer is full, Uptrace starts to drop measures.
  #buffer_size: 100000

  # The number of measures to insert in a single query.
  #batch_size: 10000

# Alerting rules.
alerting:
  rules:
    - name: check goroutines
      metrics:
        - process.runtime.go.goroutines as $goroutines
      expr: $goroutines >= 0 group by host.name
      for: 5m
      projects: [1]

alertmanager:
  urls:
    - 'http://localhost:9093/api/v2/alerts'

# To require authentication, uncomment the following section.
# users:
#   - id: 1
#     username: uptrace
#     password: uptrace

projects:
  # Conventionally, the first project is used for self-monitoring.
  - id: 1
    name: Uptrace
    # Token grants write access to the project. Keep a secret.
    token: project1_secret_token
    pinned_attrs:
      - service.name
      - host.name
      - deployment.environment

  - id: 2
    name: My project
    token: project2_secret_token
    pinned_attrs:
      - service.name
      - host.name
      - deployment.environment

# SQLite database is used to store metadata such us metric names, dashboards, alerts, and so on.
db:
  dsn: 'file:uptrace.sqlite3'

# Metrics dashboard templates.
dashboards:
  - https://raw.githubusercontent.com/uptrace/uptrace/master/config/dashboard-templates/go.yml
  - https://raw.githubusercontent.com/uptrace/uptrace/master/config/dashboard-templates/uptrace.yml
