# Prometheus config used by Uptrace.

global:
  external_labels:
    #foo: bar

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'localhost:9093'

rule_files:
  - rules.yml
